package thvardhan.ytluckyblocks.items;

import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModItems {

    //------------------------------tool mat.
    public static ToolMaterial NastySword = EnumHelper.addToolMaterial("Nastysword", 0, 20, 0, 0F, 0);
    public static ToolMaterial YTSword = EnumHelper.addToolMaterial("YTsword", 0, 1000, 0, 5F, 0);
    public static ToolMaterial MSword = EnumHelper.addToolMaterial("Msword", 0, 1000, 0, 3F, 0);
    public static ToolMaterial Black = EnumHelper.addToolMaterial("Black", 0, 2005, 0, 1F, 22);
    public static ToolMaterial Log = EnumHelper.addToolMaterial("log", 0, 4000, 0, 1.5F, 40);
    public static ToolMaterial Devil = EnumHelper.addToolMaterial("devil", 0, 5000, 0, 3F, 100);
    public static ToolMaterial Levin = EnumHelper.addToolMaterial("levin", 0, 1, 0, 996F, 0);
    public static ToolMaterial Snow = EnumHelper.addToolMaterial("snow", 0, 150, 0, 0.5F, 0);
    public static ToolMaterial Mega = EnumHelper.addToolMaterial("mega", 0, 1000, 0, 1.5F, 30);
    public static ToolMaterial Battle = EnumHelper.addToolMaterial("battle", 0, 2000, 0, 2F, 100);
    public static ToolMaterial Rainbow = EnumHelper.addToolMaterial("rainbow", 0, 300, 0, 3F, 0);


    //-----------------------------Armors
    public static ArmorMaterial DuckArmor = EnumHelper.addArmorMaterial("DuckArmor", "ytluckyblocks:duckarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LeahArmor = EnumHelper.addArmorMaterial("LeahArmor", "ytluckyblocks:leaharmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial MaxArmor = EnumHelper.addArmorMaterial("MaxArmor", "ytluckyblocks:maxarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial CassieTheCat = EnumHelper.addArmorMaterial("CassieTheCat", "ytluckyblocks:cassiethecat", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial DonutArmor = EnumHelper.addArmorMaterial("DonutArmor", "ytluckyblocks:donutarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial EvilLittleKellyArmor = EnumHelper.addArmorMaterial("EvilLittleKellyArmor", "ytluckyblocks:evillittlekellyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LittleAllyArmor = EnumHelper.addArmorMaterial("LittleAllyArmor", "ytluckyblocks:littleallyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LittleCarlyArmor = EnumHelper.addArmorMaterial("LittleCarlyArmor", "ytluckyblocks:littlecarlyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LittleDonnyArmor = EnumHelper.addArmorMaterial("LittleDonnyArmor", "ytluckyblocks:littledonnyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LittleKellyArmor = EnumHelper.addArmorMaterial("LittleKellyArmor", "ytluckyblocks:littlekellyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LittleLizardGaming = EnumHelper.addArmorMaterial("LittleLizardGaming", "ytluckyblocks:littlelizardgaming", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial MaxTheMonkeyArmor = EnumHelper.addArmorMaterial("MaxTheMonkeyArmor", "ytluckyblocks:maxthemonkeyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SharkyArmor = EnumHelper.addArmorMaterial("SharkyArmor", "ytluckyblocks:sharkyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial TinyTurtuleArmor = EnumHelper.addArmorMaterial("TinyTurtuleArmor", "ytluckyblocks:tinyturtulearmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);

    public static ArmorMaterial aphmauArmor = EnumHelper.addArmorMaterial("aphmauArmor", "ytluckyblocks:aphmauarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial ropoArmor = EnumHelper.addArmorMaterial("ropoArmor", "ytluckyblocks:ropoarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial scubaArmor = EnumHelper.addArmorMaterial("scubaArmor", "ytluckyblocks:scubaarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial crainerArmor = EnumHelper.addArmorMaterial("crainerArmor", "ytluckyblocks:crainerarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial angelArmor = EnumHelper.addArmorMaterial("angelArmor", "ytluckyblocks:angelarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);

    public static ArmorMaterial TntArmor = EnumHelper.addArmorMaterial("TntArmor", "ytluckyblocks:tnt", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LacArmor = EnumHelper.addArmorMaterial("LacArmor", "ytluckyblocks:lac", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial MrArmor = EnumHelper.addArmorMaterial("MrArmor", "ytluckyblocks:mr", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial PetaArmor = EnumHelper.addArmorMaterial("PetaArmor", "ytluckyblocks:peta", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial PinkArmor = EnumHelper.addArmorMaterial("PinkArmor", "ytluckyblocks:pink", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial VikArmor = EnumHelper.addArmorMaterial("VikArmor", "ytluckyblocks:vik", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial IHasArmor = EnumHelper.addArmorMaterial("IHasArmor", "ytluckyblocks:ihasarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LDArmor = EnumHelper.addArmorMaterial("LDArmor", "ytluckyblocks:ldarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial PrestonArmor = EnumHelper.addArmorMaterial("PrestonArmor", "ytluckyblocks:prestonarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SArmor = EnumHelper.addArmorMaterial("SArmor", "ytluckyblocks:sarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial StampyArmor = EnumHelper.addArmorMaterial("StampyArmor", "ytluckyblocks:stampyarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial ThnxArmor = EnumHelper.addArmorMaterial("ThnxArmor", "ytluckyblocks:thnxarmor", 80, new int[]{4, 8, 6, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial YtArmor = EnumHelper.addArmorMaterial("YtArmor", "ytluckyblocks:ytarmor", 100, new int[]{4, 7, 5, 4}, 1, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial AntArmor = EnumHelper.addArmorMaterial("AntArmor", "ytluckyblocks:antarmor", 80, new int[]{7, 4, 5, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial CapArmor = EnumHelper.addArmorMaterial("CapArmor", "ytluckyblocks:caparmor", 80, new int[]{4, 8, 5, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial DanArmor = EnumHelper.addArmorMaterial("DanArmor", "ytluckyblocks:danarmor", 80, new int[]{4, 7, 5, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SquidArmor = EnumHelper.addArmorMaterial("SquidArmor", "ytluckyblocks:squidarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial LogArmor = EnumHelper.addArmorMaterial("LogArmor", "ytluckyblocks:logarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial PopArmor = EnumHelper.addArmorMaterial("PopArmor", "ytluckyblocks:poparmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SpArmor = EnumHelper.addArmorMaterial("SpArmor", "ytluckyblocks:sparmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SkyArmor = EnumHelper.addArmorMaterial("SkyArmor", "ytluckyblocks:skyarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial SuperArmor = EnumHelper.addArmorMaterial("SuperArmor", "ytluckyblocks:superarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial TrueArmor = EnumHelper.addArmorMaterial("TrueArmor", "ytluckyblocks:truearmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial AlexArmor = EnumHelper.addArmorMaterial("AlexArmor", "ytluckyblocks:alexarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial BajanArmor = EnumHelper.addArmorMaterial("BajanArmor", "ytluckyblocks:bajanarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial FrizzArmor = EnumHelper.addArmorMaterial("FrizzArmor", "ytluckyblocks:frizzarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial JeromeArmor = EnumHelper.addArmorMaterial("JeromeArmor", "ytluckyblocks:jeromearmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    public static ArmorMaterial TewityArmor = EnumHelper.addArmorMaterial("TewityArmor", "ytluckyblocks:tewityarmor", 80, new int[]{4, 8, 6, 4}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
    //--------------------------------ITEMS
    public static Item nastySword;
    public static Item yt_Sword;
    public static Item m_sword;
    public static Item swordBlack;
    public static Item swordLogdotzip;
    public static Item devilSword;
    public static Item levinSword;
    public static Item snowSword;
    public static Item megaSword;
    public static Item battleAxe;
    public static Item rainbowBlade;
    public static Item mic;
    public static Item ytIcon;
    //-------------------------------ARMS
    public static Item tntHelmet;
    public static Item tntChestplate;
    public static Item tntLeggings;
    public static Item tntBoots;
    public static Item lacHelmet;
    public static Item lacChestplate;
    public static Item lacLeggings;
    public static Item lacBoots;
    public static Item mrHelmet;
    public static Item mrChestplate;
    public static Item mrLeggings;
    public static Item mrBoots;
    public static Item petaHelmet;
    public static Item petaChestplate;
    public static Item petaLeggings;
    public static Item petaBoots;
    public static Item pinkHelmet;
    public static Item pinkChestplate;
    public static Item pinkLeggings;
    public static Item pinkBoots;
    public static Item vikHelmet;
    public static Item vikChestplate;
    public static Item vikLeggings;
    public static Item vikBoots;
    public static Item ihas_Helmet;
    public static Item ihas_Chestplate;
    public static Item ihas_Leggings;
    public static Item ihas_Boots;
    public static Item ld_Helmet;
    public static Item ld_Chestplate;
    public static Item ld_Leggings;
    public static Item ld_Boots;
    public static Item preston_Helmet;
    public static Item preston_Chestplate;
    public static Item preston_Leggings;
    public static Item preston_Boots;
    public static Item s_Helmet;
    public static Item s_Chestplate;
    public static Item s_Leggings;
    public static Item s_Boots;
    public static Item stampy_Helmet;
    public static Item stampy_Chestplate;
    public static Item stampy_Leggings;
    public static Item stampy_Boots;
    public static Item thnx_Helmet;
    public static Item thnx_Chestplate;
    public static Item thnx_Leggings;
    public static Item thnx_Boots;
    public static Item ytHelmet;
    public static Item ytChestplate;
    public static Item ytLeggings;
    public static Item ytBoots;
    public static Item antHelmet;
    public static Item antChestplate;
    public static Item antLeggings;
    public static Item antBoots;
    public static Item capHelmet;
    public static Item capChestplate;
    public static Item capLeggings;
    public static Item capBoots;
    public static Item danHelmet;
    public static Item danChestplate;
    public static Item danLeggings;
    public static Item danBoots;
    public static Item squidHelmet;
    public static Item squidChestplate;
    public static Item squidLeggings;
    public static Item squidBoots;
    public static Item logHelmet;
    public static Item logChestplate;
    public static Item logLeggings;
    public static Item logBoots;
    public static Item popHelmet;
    public static Item popChestplate;
    public static Item popLeggings;
    public static Item popBoots;
    public static Item spHelmet;
    public static Item spChestplate;
    public static Item spLeggings;
    public static Item spBoots;
    public static Item skyHelmet;
    public static Item skyChestplate;
    public static Item skyLeggings;
    public static Item skyBoots;
    public static Item superHelmet;
    public static Item superChestplate;
    public static Item superLeggings;
    public static Item superBoots;
    public static Item trueHelmet;
    public static Item trueChestplate;
    public static Item trueLeggings;
    public static Item trueBoots;
    public static Item alexHelmet;
    public static Item alexChestplate;
    public static Item alexLeggings;
    public static Item alexBoots;
    public static Item bajanHelmet;
    public static Item bajanChestplate;
    public static Item bajanLeggings;
    public static Item bajanBoots;
    public static Item frizzHelmet;
    public static Item frizzChestplate;
    public static Item frizzLeggings;
    public static Item frizzBoots;
    public static Item jeromeHelmet;
    public static Item jeromeChestplate;
    public static Item jeromeLeggings;
    public static Item jeromeBoots;
    public static Item tewityHelmet;
    public static Item tewityChestplate;
    public static Item tewityLeggings;
    public static Item tewityBoots;

    public static Item duckHelmet;
    public static Item duckChestplate;
    public static Item duckLeggings;
    public static Item duckBoots;
    public static Item leahHelmet;
    public static Item leahChestplate;
    public static Item leahLeggings;
    public static Item leahBoots;
    public static Item maxHelmet;
    public static Item maxChestplate;
    public static Item maxLeggings;
    public static Item maxBoots;
    public static Item cassieTheCatHelmet;
    public static Item cassieTheCatChestplate;
    public static Item cassieTheCatLeggings;
    public static Item cassieTheCatBoots;
    public static Item donutHelmet;
    public static Item donutChestplate;
    public static Item donutLeggings;
    public static Item donutBoots;
    public static Item evilLittleKellyHelmet;
    public static Item evilLittleKellyChestplate;
    public static Item evilLittleKellyLeggings;
    public static Item evilLittleKellyBoots;
    public static Item allyHelmet;
    public static Item allyChestplate;
    public static Item allyLeggings;
    public static Item allyBoots;
    public static Item carlyHelmet;
    public static Item carlyChestplate;
    public static Item carlyLeggings;
    public static Item carlyBoots;
    public static Item donnyHelmet;
    public static Item donnyChestplate;
    public static Item donnyLeggings;
    public static Item donnyBoots;
    public static Item littleKellyHelmet;
    public static Item littleKellyChestplate;
    public static Item littleKellyLeggings;
    public static Item littleKellyBoots;
    public static Item littlelizardHelmet;
    public static Item littlelizardChestplate;
    public static Item littlelizardLeggings;
    public static Item littlelizardBoots;
    public static Item monkeyHelmet;
    public static Item monkeyChestplate;
    public static Item monkeyLeggings;
    public static Item monkeyBoots;
    public static Item sharkyHelmet;
    public static Item sharkyChestplate;
    public static Item sharkyLeggings;
    public static Item sharkyBoots;
    public static Item turtleHelmet;
    public static Item turtleChestplate;
    public static Item turtleLeggings;
    public static Item turtleBoots;


    public static Item aphmauHelmet;
    public static Item aphmauChestplate;
    public static Item aphmauLeggings;
    public static Item aphmauBoots;
    public static Item ropoHelmet;
    public static Item ropoChestplate;
    public static Item ropoLeggings;
    public static Item ropoBoots;
    public static Item scubaHelmet;
    public static Item scubaChestplate;
    public static Item scubaLeggings;
    public static Item scubaBoots;
    public static Item crainerHelmet;
    public static Item crainerChestplate;
    public static Item crainerLeggings;
    public static Item crainerBoots;
    public static Item angelHelmet;
    public static Item angelChestplate;
    public static Item angelLeggings;
    public static Item angelBoots;


    public static void createTools() {

        //-------------------ITEMS

        GameRegistry.registerItem(nastySword = new NastySword("nasty_sword", NastySword), "nasty_sword");
        GameRegistry.registerItem(swordBlack = new SwordBlack("black_sword", Black), "black_sword");
        GameRegistry.registerItem(swordLogdotzip = new SwordLogdotzip("logdotzip_sword", Log), "logdotzip_sword");
        GameRegistry.registerItem(devilSword = new DevilSword("devil_sword", Devil), "devil_sword");
        GameRegistry.registerItem(levinSword = new LevinSword("levin_sword", Levin), "levin_sword");
        GameRegistry.registerItem(mic = new MicItem("mic"), "mic");
        GameRegistry.registerItem(ytIcon = new YtIcon("yticon"), "yticon");
        GameRegistry.registerItem(snowSword = new SnowSword("snow_sword", Snow), "snow_sword");
        GameRegistry.registerItem(megaSword = new MagaSword("mega_sword", Mega), "mega_sword");
        GameRegistry.registerItem(battleAxe = new BattleAxe("battle_axe", Battle), "battle_axe");
        GameRegistry.registerItem(rainbowBlade = new RainbowBlade("rainbow_blade", Rainbow), "rainbow_blade");
        GameRegistry.registerItem(m_sword = new M_sword("m_sword", MSword), "m_sword");
        GameRegistry.registerItem(yt_Sword = new YT_Sword("yt_sword", YTSword), "yt_sword");

        //-------------------ARMS
        GameRegistry.registerItem(tntHelmet = new ItemModArmor("tnt_helmet", TntArmor, 1, EntityEquipmentSlot.HEAD), "tnt_helmet");
        GameRegistry.registerItem(tntChestplate = new ItemModArmor("tnt_chestplate", TntArmor, 1, EntityEquipmentSlot.CHEST), "tnt_chestplate");
        GameRegistry.registerItem(tntLeggings = new ItemModArmor("tnt_leggings", TntArmor, 2, EntityEquipmentSlot.LEGS), "tnt_leggings");
        GameRegistry.registerItem(tntBoots = new ItemModArmor("tnt_boots", TntArmor, 1, EntityEquipmentSlot.FEET), "tnt_boots");
        GameRegistry.registerItem(lacHelmet = new ItemModArmor("lac_helmet", LacArmor, 1, EntityEquipmentSlot.HEAD), "lac_helmet");
        GameRegistry.registerItem(lacChestplate = new ItemModArmor("lac_chestplate", LacArmor, 1, EntityEquipmentSlot.CHEST), "lac_chestplate");
        GameRegistry.registerItem(lacLeggings = new ItemModArmor("lac_leggings", LacArmor, 2, EntityEquipmentSlot.LEGS), "lac_leggings");
        GameRegistry.registerItem(lacBoots = new ItemModArmor("lac_boots", LacArmor, 1, EntityEquipmentSlot.FEET), "lac_boots");
        GameRegistry.registerItem(mrHelmet = new ItemModArmor("mr_helmet", MrArmor, 1, EntityEquipmentSlot.HEAD), "mr_helmet");
        GameRegistry.registerItem(mrChestplate = new ItemModArmor("mr_chestplate", MrArmor, 1, EntityEquipmentSlot.CHEST), "mr_chestplate");
        GameRegistry.registerItem(mrLeggings = new ItemModArmor("mr_leggings", MrArmor, 2, EntityEquipmentSlot.LEGS), "mr_leggings");
        GameRegistry.registerItem(mrBoots = new ItemModArmor("mr_boots", MrArmor, 1, EntityEquipmentSlot.FEET), "mr_boots");
        GameRegistry.registerItem(petaHelmet = new ItemModArmor("peta_helmet", PetaArmor, 1, EntityEquipmentSlot.HEAD), "peta_helmet");
        GameRegistry.registerItem(petaChestplate = new ItemModArmor("peta_chestplate", PetaArmor, 1, EntityEquipmentSlot.CHEST), "peta_chestplate");
        GameRegistry.registerItem(petaLeggings = new ItemModArmor("peta_leggings", PetaArmor, 2, EntityEquipmentSlot.LEGS), "peta_leggings");
        GameRegistry.registerItem(petaBoots = new ItemModArmor("peta_boots", PetaArmor, 1, EntityEquipmentSlot.FEET), "peta_boots");
        GameRegistry.registerItem(pinkHelmet = new ItemModArmor("pink_helmet", PinkArmor, 1, EntityEquipmentSlot.HEAD), "pink_helmet");
        GameRegistry.registerItem(pinkChestplate = new ItemModArmor("pink_chestplate", PinkArmor, 1, EntityEquipmentSlot.CHEST), "pink_chestplate");
        GameRegistry.registerItem(pinkLeggings = new ItemModArmor("pink_leggings", PinkArmor, 2, EntityEquipmentSlot.LEGS), "pink_leggings");
        GameRegistry.registerItem(pinkBoots = new ItemModArmor("pink_boots", PinkArmor, 1, EntityEquipmentSlot.FEET), "pink_boots");
        GameRegistry.registerItem(vikHelmet = new ItemModArmor("vik_helmet", VikArmor, 1, EntityEquipmentSlot.HEAD), "vik_helmet");
        GameRegistry.registerItem(vikChestplate = new ItemModArmor("vik_chestplate", VikArmor, 1, EntityEquipmentSlot.CHEST), "vik_chestplate");
        GameRegistry.registerItem(vikLeggings = new ItemModArmor("vik_leggings", VikArmor, 2, EntityEquipmentSlot.LEGS), "vik_leggings");
        GameRegistry.registerItem(vikBoots = new ItemModArmor("vik_boots", VikArmor, 1, EntityEquipmentSlot.FEET), "vik_boots");

        GameRegistry.registerItem(ytHelmet = new ItemModArmor("yt_helmet", YtArmor, 1, EntityEquipmentSlot.HEAD), "yt_helmet");
        GameRegistry.registerItem(ytChestplate = new ItemModArmor("yt_chestplate", YtArmor, 1, EntityEquipmentSlot.CHEST), "yt_chestplate");
        GameRegistry.registerItem(ytLeggings = new ItemModArmor("yt_leggings", YtArmor, 2, EntityEquipmentSlot.LEGS), "yt_leggings");
        GameRegistry.registerItem(ytBoots = new ItemModArmor("yt_boots", YtArmor, 1, EntityEquipmentSlot.FEET), "yt_boots");
        GameRegistry.registerItem(antHelmet = new ItemModArmor("ant_helmet", AntArmor, 1, EntityEquipmentSlot.HEAD), "ant_helmet");
        GameRegistry.registerItem(antChestplate = new ItemModArmor("ant_chestplate", AntArmor, 1, EntityEquipmentSlot.CHEST), "ant_chestplate");
        GameRegistry.registerItem(antLeggings = new ItemModArmor("ant_leggings", AntArmor, 2, EntityEquipmentSlot.LEGS), "ant_leggings");
        GameRegistry.registerItem(antBoots = new ItemModArmor("ant_boots", AntArmor, 1, EntityEquipmentSlot.FEET), "ant_boots");
        GameRegistry.registerItem(capHelmet = new ItemModArmor("cap_helmet", CapArmor, 1, EntityEquipmentSlot.HEAD), "cap_helmet");
        GameRegistry.registerItem(capChestplate = new ItemModArmor("cap_chestplate", CapArmor, 1, EntityEquipmentSlot.CHEST), "cap_chestplate");
        GameRegistry.registerItem(capLeggings = new ItemModArmor("cap_leggings", CapArmor, 2, EntityEquipmentSlot.LEGS), "cap_leggings");
        GameRegistry.registerItem(capBoots = new ItemModArmor("cap_boots", CapArmor, 1, EntityEquipmentSlot.FEET), "cap_boots");
        GameRegistry.registerItem(danHelmet = new ItemModArmor("dan_helmet", DanArmor, 1, EntityEquipmentSlot.HEAD), "dan_helmet");
        GameRegistry.registerItem(danChestplate = new ItemModArmor("dan_chestplate", DanArmor, 1, EntityEquipmentSlot.CHEST), "dan_chestplate");
        GameRegistry.registerItem(danLeggings = new ItemModArmor("dan_leggings", DanArmor, 2, EntityEquipmentSlot.LEGS), "dan_leggings");
        GameRegistry.registerItem(danBoots = new ItemModArmor("dan_boots", DanArmor, 1, EntityEquipmentSlot.FEET), "dan_boots");
        GameRegistry.registerItem(squidHelmet = new ItemModArmor("squid_helmet", SquidArmor, 1, EntityEquipmentSlot.HEAD), "squid_helmet");
        GameRegistry.registerItem(squidChestplate = new ItemModArmor("squid_chestplate", SquidArmor, 1, EntityEquipmentSlot.CHEST), "squid_chestplate");
        GameRegistry.registerItem(squidLeggings = new ItemModArmor("squid_leggings", SquidArmor, 2, EntityEquipmentSlot.LEGS), "squid_leggings");
        GameRegistry.registerItem(squidBoots = new ItemModArmor("squid_boots", SquidArmor, 1, EntityEquipmentSlot.FEET), "squid_boots");
        GameRegistry.registerItem(logHelmet = new ItemModArmor("log_helmet", LogArmor, 1, EntityEquipmentSlot.HEAD), "log_helmet");
        GameRegistry.registerItem(logChestplate = new ItemModArmor("log_chestplate", LogArmor, 1, EntityEquipmentSlot.CHEST), "log_chestplate");
        GameRegistry.registerItem(logLeggings = new ItemModArmor("log_leggings", LogArmor, 2, EntityEquipmentSlot.LEGS), "log_leggings");
        GameRegistry.registerItem(logBoots = new ItemModArmor("log_boots", LogArmor, 1, EntityEquipmentSlot.FEET), "log_boots");
        GameRegistry.registerItem(popHelmet = new ItemModArmor("pop_helmet", PopArmor, 1, EntityEquipmentSlot.HEAD), "pop_helmet");
        GameRegistry.registerItem(popChestplate = new ItemModArmor("pop_chestplate", PopArmor, 1, EntityEquipmentSlot.CHEST), "pop_chestplate");
        GameRegistry.registerItem(popLeggings = new ItemModArmor("pop_leggings", PopArmor, 2, EntityEquipmentSlot.LEGS), "pop_leggings");
        GameRegistry.registerItem(popBoots = new ItemModArmor("pop_boots", PopArmor, 1, EntityEquipmentSlot.FEET), "pop_boots");
        GameRegistry.registerItem(spHelmet = new ItemModArmor("sp_helmet", SpArmor, 1, EntityEquipmentSlot.HEAD), "sp_helmet");
        GameRegistry.registerItem(spChestplate = new ItemModArmor("sp_chestplate", SpArmor, 1, EntityEquipmentSlot.CHEST), "sp_chestplate");
        GameRegistry.registerItem(spLeggings = new ItemModArmor("sp_leggings", SpArmor, 2, EntityEquipmentSlot.LEGS), "sp_leggings");
        GameRegistry.registerItem(spBoots = new ItemModArmor("sp_boots", SpArmor, 1, EntityEquipmentSlot.FEET), "sp_boots");
        GameRegistry.registerItem(skyHelmet = new ItemModArmor("sky_helmet", SkyArmor, 1, EntityEquipmentSlot.HEAD), "sky_helmet");
        GameRegistry.registerItem(skyChestplate = new ItemModArmor("sky_chestplate", SkyArmor, 1, EntityEquipmentSlot.CHEST), "sky_chestplate");
        GameRegistry.registerItem(skyLeggings = new ItemModArmor("sky_leggings", SkyArmor, 2, EntityEquipmentSlot.LEGS), "sky_leggings");
        GameRegistry.registerItem(skyBoots = new ItemModArmor("sky_boots", SkyArmor, 1, EntityEquipmentSlot.FEET), "sky_boots");
        GameRegistry.registerItem(superHelmet = new ItemModArmor("super_helmet", SuperArmor, 1, EntityEquipmentSlot.HEAD), "super_helmet");
        GameRegistry.registerItem(superChestplate = new ItemModArmor("super_chestplate", SuperArmor, 1, EntityEquipmentSlot.CHEST), "super_chestplate");
        GameRegistry.registerItem(superLeggings = new ItemModArmor("super_leggings", SuperArmor, 2, EntityEquipmentSlot.LEGS), "super_leggings");
        GameRegistry.registerItem(superBoots = new ItemModArmor("super_boots", SuperArmor, 1, EntityEquipmentSlot.FEET), "super_boots");
        GameRegistry.registerItem(trueHelmet = new ItemModArmor("true_helmet", TrueArmor, 1, EntityEquipmentSlot.HEAD), "true_helmet");
        GameRegistry.registerItem(trueChestplate = new ItemModArmor("true_chestplate", TrueArmor, 1, EntityEquipmentSlot.CHEST), "true_chestplate");
        GameRegistry.registerItem(trueLeggings = new ItemModArmor("true_leggings", TrueArmor, 2, EntityEquipmentSlot.LEGS), "true_leggings");
        GameRegistry.registerItem(trueBoots = new ItemModArmor("true_boots", TrueArmor, 1, EntityEquipmentSlot.FEET), "true_boots");
        GameRegistry.registerItem(alexHelmet = new ItemModArmor("alex_helmet", AlexArmor, 1, EntityEquipmentSlot.HEAD), "alex_helmet");
        GameRegistry.registerItem(alexChestplate = new ItemModArmor("alex_chestplate", AlexArmor, 1, EntityEquipmentSlot.CHEST), "alex_chestplate");
        GameRegistry.registerItem(alexLeggings = new ItemModArmor("alex_leggings", AlexArmor, 2, EntityEquipmentSlot.LEGS), "alex_leggings");
        GameRegistry.registerItem(alexBoots = new ItemModArmor("alex_boots", AlexArmor, 1, EntityEquipmentSlot.FEET), "alex_boots");
        GameRegistry.registerItem(bajanHelmet = new ItemModArmor("bajan_helmet", BajanArmor, 1, EntityEquipmentSlot.HEAD), "bajan_helmet");
        GameRegistry.registerItem(bajanChestplate = new ItemModArmor("bajan_chestplate", BajanArmor, 1, EntityEquipmentSlot.CHEST), "bajan_chestplate");
        GameRegistry.registerItem(bajanLeggings = new ItemModArmor("bajan_leggings", BajanArmor, 2, EntityEquipmentSlot.LEGS), "bajan_leggings");
        GameRegistry.registerItem(bajanBoots = new ItemModArmor("bajan_boots", BajanArmor, 1, EntityEquipmentSlot.FEET), "bajan_boots");
        GameRegistry.registerItem(frizzHelmet = new ItemModArmor("frizz_helmet", FrizzArmor, 1, EntityEquipmentSlot.HEAD), "frizz_helmet");
        GameRegistry.registerItem(frizzChestplate = new ItemModArmor("frizz_chestplate", FrizzArmor, 1, EntityEquipmentSlot.CHEST), "frizz_chestplate");
        GameRegistry.registerItem(frizzLeggings = new ItemModArmor("frizz_leggings", FrizzArmor, 2, EntityEquipmentSlot.LEGS), "frizz_leggings");
        GameRegistry.registerItem(frizzBoots = new ItemModArmor("frizz_boots", FrizzArmor, 1, EntityEquipmentSlot.FEET), "frizz_boots");
        GameRegistry.registerItem(jeromeHelmet = new ItemModArmor("jerome_helmet", JeromeArmor, 1, EntityEquipmentSlot.HEAD), "jerome_helmet");
        GameRegistry.registerItem(jeromeChestplate = new ItemModArmor("jerome_chestplate", JeromeArmor, 1, EntityEquipmentSlot.CHEST), "jerome_chestplate");
        GameRegistry.registerItem(jeromeLeggings = new ItemModArmor("jerome_leggings", JeromeArmor, 2, EntityEquipmentSlot.LEGS), "jerome_leggings");
        GameRegistry.registerItem(jeromeBoots = new ItemModArmor("jerome_boots", JeromeArmor, 1, EntityEquipmentSlot.FEET), "jerome_boots");
        GameRegistry.registerItem(tewityHelmet = new ItemModArmor("tewity_helmet", TewityArmor, 1, EntityEquipmentSlot.HEAD), "tewity_helmet");
        GameRegistry.registerItem(tewityChestplate = new ItemModArmor("tewity_chestplate", TewityArmor, 1, EntityEquipmentSlot.CHEST), "tewity_chestplate");
        GameRegistry.registerItem(tewityLeggings = new ItemModArmor("tewity_leggings", TewityArmor, 2, EntityEquipmentSlot.LEGS), "tewity_leggings");
        GameRegistry.registerItem(tewityBoots = new ItemModArmor("tewity_boots", TewityArmor, 1, EntityEquipmentSlot.FEET), "tewity_boots");
        GameRegistry.registerItem(ihas_Helmet = new ItemModArmor("ihas_helmet", IHasArmor, 1, EntityEquipmentSlot.HEAD), "ihas_helmet");
        GameRegistry.registerItem(ihas_Chestplate = new ItemModArmor("ihas_chestplate", IHasArmor, 1, EntityEquipmentSlot.CHEST), "ihas_chestplate");
        GameRegistry.registerItem(ihas_Leggings = new ItemModArmor("ihas_leggings", IHasArmor, 2, EntityEquipmentSlot.LEGS), "ihas_leggings");
        GameRegistry.registerItem(ihas_Boots = new ItemModArmor("ihas_boots", IHasArmor, 1, EntityEquipmentSlot.FEET), "ihas_boots");
        GameRegistry.registerItem(ld_Helmet = new ItemModArmor("ld_helmet", LDArmor, 1, EntityEquipmentSlot.HEAD), "ld_helmet");
        GameRegistry.registerItem(ld_Chestplate = new ItemModArmor("ld_chestplate", LDArmor, 1, EntityEquipmentSlot.CHEST), "ld_chestplate");
        GameRegistry.registerItem(ld_Leggings = new ItemModArmor("ld_leggings", LDArmor, 2, EntityEquipmentSlot.LEGS), "ld_leggings");
        GameRegistry.registerItem(ld_Boots = new ItemModArmor("ld_boots", LDArmor, 1, EntityEquipmentSlot.FEET), "ld_boots");
        GameRegistry.registerItem(preston_Helmet = new ItemModArmor("preston_helmet", PrestonArmor, 1, EntityEquipmentSlot.HEAD), "preston_helmet");
        GameRegistry.registerItem(preston_Chestplate = new ItemModArmor("preston_chestplate", PrestonArmor, 1, EntityEquipmentSlot.CHEST), "preston_chestplate");
        GameRegistry.registerItem(preston_Leggings = new ItemModArmor("preston_leggings", PrestonArmor, 2, EntityEquipmentSlot.LEGS), "preston_leggings");
        GameRegistry.registerItem(preston_Boots = new ItemModArmor("preston_boots", PrestonArmor, 1, EntityEquipmentSlot.FEET), "preston_boots");
        GameRegistry.registerItem(s_Helmet = new ItemModArmor("s_helmet", SArmor, 1, EntityEquipmentSlot.HEAD), "s_helmet");
        GameRegistry.registerItem(s_Chestplate = new ItemModArmor("s_chestplate", SArmor, 1, EntityEquipmentSlot.CHEST), "s_chestplate");
        GameRegistry.registerItem(s_Leggings = new ItemModArmor("s_leggings", SArmor, 2, EntityEquipmentSlot.LEGS), "s_leggings");
        GameRegistry.registerItem(s_Boots = new ItemModArmor("s_boots", SArmor, 1, EntityEquipmentSlot.FEET), "s_boots");
        GameRegistry.registerItem(stampy_Helmet = new ItemModArmor("stampy_helmet", StampyArmor, 1, EntityEquipmentSlot.HEAD), "stampy_helmet");
        GameRegistry.registerItem(stampy_Chestplate = new ItemModArmor("stampy_chestplate", StampyArmor, 1, EntityEquipmentSlot.CHEST), "stampy_chestplate");
        GameRegistry.registerItem(stampy_Leggings = new ItemModArmor("stampy_leggings", StampyArmor, 2, EntityEquipmentSlot.LEGS), "stampy_leggings");
        GameRegistry.registerItem(stampy_Boots = new ItemModArmor("stampy_boots", StampyArmor, 1, EntityEquipmentSlot.FEET), "stampy_boots");
        GameRegistry.registerItem(thnx_Helmet = new ItemModArmor("thnx_helmet", ThnxArmor, 1, EntityEquipmentSlot.HEAD), "thnx_helmet");
        GameRegistry.registerItem(thnx_Chestplate = new ItemModArmor("thnx_chestplate", ThnxArmor, 1, EntityEquipmentSlot.CHEST), "thnx_chestplate");
        GameRegistry.registerItem(thnx_Leggings = new ItemModArmor("thnx_leggings", ThnxArmor, 2, EntityEquipmentSlot.LEGS), "thnx_leggings");
        GameRegistry.registerItem(thnx_Boots = new ItemModArmor("thnx_boots", ThnxArmor, 1, EntityEquipmentSlot.FEET), "thnx_boots");

        GameRegistry.registerItem(duckHelmet = new ItemModArmor("duckhelmet", DuckArmor, 1, EntityEquipmentSlot.HEAD), "duckhelmet");
        GameRegistry.registerItem(duckChestplate = new ItemModArmor("duckchestplate", DuckArmor, 1, EntityEquipmentSlot.CHEST), "duckchestplate");
        GameRegistry.registerItem(duckLeggings = new ItemModArmor("duckleggings", DuckArmor, 2, EntityEquipmentSlot.LEGS), "duckleggings");
        GameRegistry.registerItem(duckBoots = new ItemModArmor("duckboots", DuckArmor, 1, EntityEquipmentSlot.FEET), "duckboots");
        GameRegistry.registerItem(leahHelmet = new ItemModArmor("leahhelmet", LeahArmor, 1, EntityEquipmentSlot.HEAD), "leahhelmet");
        GameRegistry.registerItem(leahChestplate = new ItemModArmor("leahchestplate", LeahArmor, 1, EntityEquipmentSlot.CHEST), "leahchestplate");
        GameRegistry.registerItem(leahLeggings = new ItemModArmor("leahleggings", LeahArmor, 2, EntityEquipmentSlot.LEGS), "leahleggings");
        GameRegistry.registerItem(leahBoots = new ItemModArmor("leahboots", LeahArmor, 1, EntityEquipmentSlot.FEET), "leahboots");
        GameRegistry.registerItem(maxHelmet = new ItemModArmor("maxhelmet", MaxArmor, 1, EntityEquipmentSlot.HEAD), "maxhelmet");
        GameRegistry.registerItem(maxChestplate = new ItemModArmor("maxchestplate", MaxArmor, 1, EntityEquipmentSlot.CHEST), "maxchestplate");
        GameRegistry.registerItem(maxLeggings = new ItemModArmor("maxleggings", MaxArmor, 2, EntityEquipmentSlot.LEGS), "maxleggings");
        GameRegistry.registerItem(maxBoots = new ItemModArmor("maxboots", MaxArmor, 1, EntityEquipmentSlot.FEET), "maxboots");
        GameRegistry.registerItem(cassieTheCatHelmet = new ItemModArmor("cassiethecathelmet", CassieTheCat, 1, EntityEquipmentSlot.HEAD), "cassiethecathelmet");
        GameRegistry.registerItem(cassieTheCatChestplate = new ItemModArmor("cassiethecatchestplate", CassieTheCat, 1, EntityEquipmentSlot.CHEST), "cassiethecatchestplate");
        GameRegistry.registerItem(cassieTheCatLeggings = new ItemModArmor("cassiethecatleggings", CassieTheCat, 2, EntityEquipmentSlot.LEGS), "cassiethecatleggings");
        GameRegistry.registerItem(cassieTheCatBoots = new ItemModArmor("cassiethecatboots", CassieTheCat, 1, EntityEquipmentSlot.FEET), "cassiethecatboots");
        GameRegistry.registerItem(donutHelmet = new ItemModArmor("donuthelmet", DonutArmor, 1, EntityEquipmentSlot.HEAD), "donuthelmet");
        GameRegistry.registerItem(donutChestplate = new ItemModArmor("donutchestplate", DonutArmor, 1, EntityEquipmentSlot.CHEST), "donutchestplate");
        GameRegistry.registerItem(donutLeggings = new ItemModArmor("donutleggings", DonutArmor, 2, EntityEquipmentSlot.LEGS), "donutleggings");
        GameRegistry.registerItem(donutBoots = new ItemModArmor("donutboots", DonutArmor, 1, EntityEquipmentSlot.FEET), "donutboots");
        GameRegistry.registerItem(evilLittleKellyHelmet = new ItemModArmor("evillittlekellyhelmet", EvilLittleKellyArmor, 1, EntityEquipmentSlot.HEAD), "evillittlekellyhelmet");
        GameRegistry.registerItem(evilLittleKellyChestplate = new ItemModArmor("evillittlekellychestplate", EvilLittleKellyArmor, 1, EntityEquipmentSlot.CHEST), "evillittlekellychestplate");
        GameRegistry.registerItem(evilLittleKellyLeggings = new ItemModArmor("evillittlekellyleggings", EvilLittleKellyArmor, 2, EntityEquipmentSlot.LEGS), "evillittlekellyleggings");
        GameRegistry.registerItem(evilLittleKellyBoots = new ItemModArmor("evillittlekellyboots", EvilLittleKellyArmor, 1, EntityEquipmentSlot.FEET), "evillittlekellyboots");
        GameRegistry.registerItem(allyHelmet = new ItemModArmor("allyhelmet", LittleAllyArmor, 1, EntityEquipmentSlot.HEAD), "allyhelmet");
        GameRegistry.registerItem(allyChestplate = new ItemModArmor("allychestplate", LittleAllyArmor, 1, EntityEquipmentSlot.CHEST), "allychestplate");
        GameRegistry.registerItem(allyLeggings = new ItemModArmor("allyleggings", LittleAllyArmor, 2, EntityEquipmentSlot.LEGS), "allyleggings");
        GameRegistry.registerItem(allyBoots = new ItemModArmor("allyboots", LittleAllyArmor, 1, EntityEquipmentSlot.FEET), "allyboots");
        GameRegistry.registerItem(carlyHelmet = new ItemModArmor("carlyhelmet", LittleCarlyArmor, 1, EntityEquipmentSlot.HEAD), "carlyhelmet");
        GameRegistry.registerItem(carlyChestplate = new ItemModArmor("carlychestplate", LittleCarlyArmor, 1, EntityEquipmentSlot.CHEST), "carlychestplate");
        GameRegistry.registerItem(carlyLeggings = new ItemModArmor("carlyleggings", LittleCarlyArmor, 2, EntityEquipmentSlot.LEGS), "carlyleggings");
        GameRegistry.registerItem(carlyBoots = new ItemModArmor("carlyboots", LittleCarlyArmor, 1, EntityEquipmentSlot.FEET), "carlyboots");
        GameRegistry.registerItem(donnyHelmet = new ItemModArmor("donnyhelmet", LittleDonnyArmor, 1, EntityEquipmentSlot.HEAD), "donnyhelmet");
        GameRegistry.registerItem(donnyChestplate = new ItemModArmor("donnychestplate", LittleDonnyArmor, 1, EntityEquipmentSlot.CHEST), "donnychestplate");
        GameRegistry.registerItem(donnyLeggings = new ItemModArmor("donnyleggings", LittleDonnyArmor, 2, EntityEquipmentSlot.LEGS), "donnyleggings");
        GameRegistry.registerItem(donnyBoots = new ItemModArmor("donnyboots", LittleDonnyArmor, 1, EntityEquipmentSlot.FEET), "donnyboots");
        GameRegistry.registerItem(littleKellyHelmet = new ItemModArmor("littlekellyhelmet", LittleKellyArmor, 1, EntityEquipmentSlot.HEAD), "littlekellyhelmet");
        GameRegistry.registerItem(littleKellyChestplate = new ItemModArmor("littlekellychestplate", LittleKellyArmor, 1, EntityEquipmentSlot.CHEST), "littlekellychestplate");
        GameRegistry.registerItem(littleKellyLeggings = new ItemModArmor("littlekellyleggings", LittleKellyArmor, 2, EntityEquipmentSlot.LEGS), "littlekellyleggings");
        GameRegistry.registerItem(littleKellyBoots = new ItemModArmor("littlekellyboots", LittleKellyArmor, 1, EntityEquipmentSlot.FEET), "littlekellyboots");
        GameRegistry.registerItem(littlelizardHelmet = new ItemModArmor("littlelizardhelmet", LittleLizardGaming, 1, EntityEquipmentSlot.HEAD), "littlelizardhelmet");
        GameRegistry.registerItem(littlelizardChestplate = new ItemModArmor("littlelizardchestplate", LittleLizardGaming, 1, EntityEquipmentSlot.CHEST), "littlelizardchestplate");
        GameRegistry.registerItem(littlelizardLeggings = new ItemModArmor("littlelizardleggings", LittleLizardGaming, 2, EntityEquipmentSlot.LEGS), "littlelizardleggings");
        GameRegistry.registerItem(littlelizardBoots = new ItemModArmor("littlelizardboots", LittleLizardGaming, 1, EntityEquipmentSlot.FEET), "littlelizardboots");
        GameRegistry.registerItem(monkeyHelmet = new ItemModArmor("monkeyhelmet", MaxTheMonkeyArmor, 1, EntityEquipmentSlot.HEAD), "monkeyhelmet");
        GameRegistry.registerItem(monkeyChestplate = new ItemModArmor("monkeychestplate", MaxTheMonkeyArmor, 1, EntityEquipmentSlot.CHEST), "monkeychestplate");
        GameRegistry.registerItem(monkeyLeggings = new ItemModArmor("monkeyleggings", MaxTheMonkeyArmor, 2, EntityEquipmentSlot.LEGS), "monkeyleggings");
        GameRegistry.registerItem(monkeyBoots = new ItemModArmor("monkeyboots", MaxTheMonkeyArmor, 1, EntityEquipmentSlot.FEET), "monkeyboots");
        GameRegistry.registerItem(sharkyHelmet = new ItemModArmor("sharkyhelmet", SharkyArmor, 1, EntityEquipmentSlot.HEAD), "sharkyhelmet");
        GameRegistry.registerItem(sharkyChestplate = new ItemModArmor("sharkychestplate", SharkyArmor, 1, EntityEquipmentSlot.CHEST), "sharkychestplate");
        GameRegistry.registerItem(sharkyLeggings = new ItemModArmor("sharkyleggings", SharkyArmor, 2, EntityEquipmentSlot.LEGS), "sharkyleggings");
        GameRegistry.registerItem(sharkyBoots = new ItemModArmor("sharkyboots", SharkyArmor, 1, EntityEquipmentSlot.FEET), "sharkyboots");
        GameRegistry.registerItem(turtleHelmet = new ItemModArmor("turtlehelmet", TinyTurtuleArmor, 1, EntityEquipmentSlot.HEAD), "turtlehelmet");
        GameRegistry.registerItem(turtleChestplate = new ItemModArmor("turtlechestplate", TinyTurtuleArmor, 1, EntityEquipmentSlot.CHEST), "turtlechestplate");
        GameRegistry.registerItem(turtleLeggings = new ItemModArmor("turtleleggings", TinyTurtuleArmor, 2, EntityEquipmentSlot.LEGS), "turtleleggings");
        GameRegistry.registerItem(turtleBoots = new ItemModArmor("turtleboots", TinyTurtuleArmor, 1, EntityEquipmentSlot.FEET), "turtleboots");

        GameRegistry.registerItem(aphmauHelmet = new ItemModArmor("aphmauhelmet", aphmauArmor, 1, EntityEquipmentSlot.HEAD), "aphmauhelmet");
        GameRegistry.registerItem(aphmauChestplate = new ItemModArmor("aphmauchestplate", aphmauArmor, 1, EntityEquipmentSlot.CHEST), "aphmauchestplate");
        GameRegistry.registerItem(aphmauLeggings = new ItemModArmor("aphmauleggings", aphmauArmor, 2, EntityEquipmentSlot.LEGS), "aphmauleggings");
        GameRegistry.registerItem(aphmauBoots = new ItemModArmor("aphmauboots", aphmauArmor, 1, EntityEquipmentSlot.FEET), "aphmauboots");
        GameRegistry.registerItem(ropoHelmet = new ItemModArmor("ropohelmet", ropoArmor, 1, EntityEquipmentSlot.HEAD), "ropohelmet");
        GameRegistry.registerItem(ropoChestplate = new ItemModArmor("ropochestplate", ropoArmor, 1, EntityEquipmentSlot.CHEST), "ropochestplate");
        GameRegistry.registerItem(ropoLeggings = new ItemModArmor("ropoleggings", ropoArmor, 2, EntityEquipmentSlot.LEGS), "ropoleggings");
        GameRegistry.registerItem(ropoBoots = new ItemModArmor("ropoboots", ropoArmor, 1, EntityEquipmentSlot.FEET), "ropoboots");
        GameRegistry.registerItem(scubaHelmet = new ItemModArmor("scubahelmet", scubaArmor, 1, EntityEquipmentSlot.HEAD), "scubahelmet");
        GameRegistry.registerItem(scubaChestplate = new ItemModArmor("scubachestplate", scubaArmor, 1, EntityEquipmentSlot.CHEST), "scubachestplate");
        GameRegistry.registerItem(scubaLeggings = new ItemModArmor("scubaleggings", scubaArmor, 2, EntityEquipmentSlot.LEGS), "scubaleggings");
        GameRegistry.registerItem(scubaBoots = new ItemModArmor("scubaboots", scubaArmor, 1, EntityEquipmentSlot.FEET), "scubaboots");
        GameRegistry.registerItem(crainerHelmet = new ItemModArmor("crainerhelmet", crainerArmor, 1, EntityEquipmentSlot.HEAD), "crainerhelmet");
        GameRegistry.registerItem(crainerChestplate = new ItemModArmor("crainerchestplate", crainerArmor, 1, EntityEquipmentSlot.CHEST), "crainerchestplate");
        GameRegistry.registerItem(crainerLeggings = new ItemModArmor("crainerleggings", crainerArmor, 2, EntityEquipmentSlot.LEGS), "crainerleggings");
        GameRegistry.registerItem(crainerBoots = new ItemModArmor("crainerboots", crainerArmor, 1, EntityEquipmentSlot.FEET), "crainerboots");
        GameRegistry.registerItem(angelHelmet = new ItemModArmor("angelhelmet", angelArmor, 1, EntityEquipmentSlot.HEAD), "angelhelmet");
        GameRegistry.registerItem(angelChestplate = new ItemModArmor("angelchestplate", angelArmor, 1, EntityEquipmentSlot.CHEST), "angelchestplate");
        GameRegistry.registerItem(angelLeggings = new ItemModArmor("angelleggings", angelArmor, 2, EntityEquipmentSlot.LEGS), "angelleggings");
        GameRegistry.registerItem(angelBoots = new ItemModArmor("angelboots", angelArmor, 1, EntityEquipmentSlot.FEET), "angelboots");

    }


}
